name: flutter_app_template
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Logger
  simple_logger:

  # LocalDatabase
  shared_preferences:

  # Riverpod
  flutter_hooks:
  hooks_riverpod:
  freezed_annotation:
  json_annotation:

  # Dialog
  adaptive_dialog:

  # Access local storage
  path_provider:

  # Date
  intl:

  # Reactive
  rxdart:

  # Data share
  share:

  # WebView
  flutter_inappwebview:

  # Launcher
  url_launcher:
  map_launcher:

  # Setting
  app_settings:

  # Review
  launch_review:
  app_review:

  # Text
  auto_size_text:

  # Carousel
  carousel_slider:

  # Switch
  toggle_switch:

  # Transition
  page_transition:

  # Image
  image_picker:
  image_gallery_saver:
  image_cropper:
  flutter_image_compress:
  extended_image:

  # Picker
  numberpicker:

  # PullToRefresh
  pull_to_refresh:

  # Scroll
  extended_nested_scroll_view:

  # Permission
  permission_handler:

  # Firebase
  firebase_core: ^1.14.0
  firebase_analytics:
  cloud_firestore:
  firebase_auth:
  firebase_storage:
  cloud_functions:
  firebase_messaging:
  firebase_crashlytics:

  # LocalNotification
  flutter_local_notifications: ^10.0.0-dev.5
  flutter_native_timezone:

  # Preview
  device_preview:

  # Widget
  flutter_fadein:
  flutter_cupertino_datetime_picker:
  flutter_app_badger:
  badges:
  flutter_slidable:
  dismissible_page:

  # Other
  uuid:
  package_info:
  synchronized:
  nonce:
  crypto:
  hashids2:
  encrypt:
  flutter_svg:
  recase:
  device_info:
  flutter_linkify:
  timezone:
  collection:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Static analysis
  pedantic_mono:

  # Serializer
  json_serializable:

  # Code generator
  build_runner:
  freezed:
  flutter_gen_runner:

  # Other
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - assets/

  # カスタムフォントを利用する場合はここを設定する
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# flutter_launcher_iconsを利用してアイコンのリサイズする場合はここを設定する
#flutter_icons:
#  android: true
#  ios: true
#  image_path_android: "assets/icon/icon_android.png"
#  image_path_ios: "assets/icon/icon_ios.png"
#  adaptive_icon_foreground: "assets/icon/adaptive_icon_foreground.png"
#  adaptive_icon_background: "#F4A281"

