name: flutter_app_template
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # LocalDatabase
  shared_preferences:

  # Riverpod
  hooks_riverpod:
  riverpod_annotation:

  # Hooks
  flutter_hooks:

  # PullToRefresh
  pull_to_refresh_flutter3:

  # Api
  retrofit:
  dio:

  # Entity
  freezed_annotation:

  # Launcher
  url_launcher:

  # Image
  extended_image:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Static analysis
  pedantic_mono:
  custom_lint:
  riverpod_lint:

  # Serializer
  json_serializable:

  # Code generator
  build_runner:
  freezed:
  riverpod_generator:
  retrofit_generator:

flutter:
  uses-material-design: true
